version: "3"
networks:
  dcm4chee_default:
services:
  logstash:
    image: dcm4che/logstash-dcm4chee:7.1.1-9
    ports:
      - "12201:12201/udp"
      - "8514:8514/udp"
      - "8514:8514"
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/ddcm4chee-arc/logstash/filter-hashtree:/usr/share/logstash/data/filter-hashtree
    networks:
      - dcm4chee_default
  db:
    image: dcm4che/postgres-dcm4chee:11.2-16
    logging:
      driver: gelf
        options:
          gelf-address: "udp://172.17.0.1:12201"
          tag: postgres
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/dcm4chee-arc/db:/var/lib/postgresql/data
    depends_on:
      - logstash
    networks:
      - dcm4chee_default
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-17.1
    logging:
      driver: gelf
        options:
          gelf-address: "udp://172.17.0.1:12201"
          tag: slapd
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/dcm4chee-arc/ldap:/var/lib/ldap
      - ./persistence/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
    depends_on:
      - db
    networks:
      - dcm4chee_default
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - ldap
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
    ports:
      - "5601:5601"
    networks:
      - dcm4chee_default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.1
    environment:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
      TAKE_FILE_OWNERSHIP: 1
      discovery.type: single-node
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - dcm4chee_default
    depends_on:
      - kibana
  keycloak:
    image: dcm4che/keycloak:6.0.1-17.0
    logging:
      driver: gelf
        options:
          gelf-address: "udp://172.17.0.1:12201"
          tag: keycloak
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      KEYCLOAK_WAIT_FOR: ldap:389 logstash:8514
    depends_on:
      - elasticsearch
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/dcm4chee-arc/keycloak:/opt/keycloak/standalone
    networks:
      - dcm4chee_default
  keycloak-gatekeeper:
    image: dcm4che/keycloak-gatekeeper:6.0.1
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.17.0.1:12201"
        tag: keycloak-gatekeeper
    ports:
      - "8643:8643"
    environment:
      PROXY_LISTEN: :8643
      PROXY_REDIRECTION_URL: https://172.17.0.1:8643
      PROXY_UPSTREAM_URL: http://kibana:5601
      PROXY_DISCOVERY_URL: https://172.17.0.1:8843/auth/realms/dcm4che
      PROXY_CLIENT_ID: kibana
      PROXY_CLIENT_SECRET: 968956a3-582b-4f8c-9d09-249fc9f74c35
      PROXY_ENCRYPTION_KEY: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
    command:
      - "--openid-provider-timeout=120s"
      - "--tls-cert=/etc/certs/cert.pem"
      - "--tls-private-key=/etc/certs/key.pem"
      - "--skip-openid-provider-tls-verify=true"
      - "--enable-refresh-tokens=true"
      - "--resources=uri=/*|roles=auditlog"
    depends_on:
      - keycloak
      - kibana
    networks:
      - dcm4chee_default
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.17.1-secure
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.17.0.1:12201"
        tag: dcm4chee-arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432 logstash:8514
    depends_on:
      - ldap
      - keycloak
      - db
      - keycloak-gatekeeper
    volumes:
      - ./persistence/etc/localtime:/etc/localtime:ro
      - ./persistence/etc/timezone:/etc/timezone:ro
      - ./persistence/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - ./persistence/dcm4chee-arc/storage:/storage
    networks:
      - dcm4chee_default